import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger'
import { Type } from 'class-transformer'
import {
  ArrayNotEmpty,
  IsArray,
  IsInt,
  IsNotEmpty,
  IsObject,
  IsOptional,
  IsString,
  Min,
  ValidateNested,
} from 'class-validator'

export class MediaCipheringDto {
  @ApiProperty({ description: 'Algorithm the media at the uri is encrypted with', example: 'aes-256-gcm' })
  @IsString()
  @IsNotEmpty()
  algorithm!: string

  @ApiProperty({ description: 'Parameters of the algorithm', type: Object })
  @IsObject()
  parameters!: Record<string, unknown>
}

export class SharedMediaItemDto {
  @ApiPropertyOptional({ description: 'Item identifier, generated by the agent when absent' })
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  id?: string

  @ApiProperty({ description: 'Where the media can be fetched from', example: 'https://media.example/1' })
  @IsString()
  @IsNotEmpty()
  uri!: string

  @ApiProperty({ description: 'Media type of the item', example: 'image/png' })
  @IsString()
  @IsNotEmpty()
  mimeType!: string

  @ApiPropertyOptional({ description: 'Name of the file' })
  @IsOptional()
  @IsString()
  fileName?: string

  @ApiPropertyOptional({ description: 'Text that describes the item' })
  @IsOptional()
  @IsString()
  description?: string

  @ApiPropertyOptional({ description: 'Size of the media, in bytes' })
  @IsOptional()
  @IsInt()
  @Min(0)
  byteCount?: number

  @ApiPropertyOptional({ type: MediaCipheringDto, description: 'Set when the media is encrypted' })
  @IsOptional()
  @ValidateNested()
  @Type(() => MediaCipheringDto)
  ciphering?: MediaCipheringDto

  @ApiPropertyOptional({ description: 'Anything else the peer should know about the item', type: Object })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>
}

export class ShareMediaBodyDto {
  @ApiProperty({ description: 'Connection to share the items on', example: 'conn-1234-5678' })
  @IsString()
  @IsNotEmpty()
  connectionId!: string

  @ApiPropertyOptional({ description: 'Text that describes the share' })
  @IsOptional()
  @IsString()
  description?: string

  @ApiPropertyOptional({ description: 'Thread of the request-media message this share answers' })
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  threadId?: string

  @ApiProperty({ type: [SharedMediaItemDto], description: 'The items to share' })
  @IsArray()
  @ArrayNotEmpty()
  @ValidateNested({ each: true })
  @Type(() => SharedMediaItemDto)
  items!: SharedMediaItemDto[]
}
