{{- if and .Values.agentSecret.create (not .Values.agentSecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
stringData:
{{- range .Values.agentSecret.env }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
{{- end }}
