services:
  vs-agent:
    build: 
      context: ../..
      dockerfile: ./apps/vs-agent/Dockerfile
    image: vs-agent
    container_name: verifier-vs-agent
    restart: always
    networks:
      - verifier
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - AGENT_ENDPOINT=ws://192.168.100.105:3001
      - AGENT_INVITATION_IMAGE_URL=http://192.168.100.105:3001/avatar.png
      - PUBLIC_API_BASE_URL=http://192.168.100.105:3001
      - AGENT_LABEL=Verifier Agent
      - USE_CORS=true
      - EVENTS_BASE_URL=http://verifier-backend:5100
    volumes:
      - ./afj:/root/.afj

  verifier-backend:
    build: 
      context: ../..
      dockerfile: ./examples/verifier/Dockerfile
    image: vs-agent-verifier
    container_name: verifier-backend
    restart: always
    networks:
      - verifier
    ports:
      - 5100:5100
    environment:
      - PORT=5100
      - VS_AGENT_ADMIN_BASE_URL=http://verifier-vs-agent:3000
      - PUBLIC_BASE_URL=http://10.82.14.12:5100

networks:
  verifier:
