services:
  vs-agent:
    build:
      context: ../..
      dockerfile: ./apps/vs-agent/Dockerfile
      target: vs-agent-mrtd
    image: vs-agent
    container_name: chatbot-vs-agent
    restart: always
    networks:
      - chatbot
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - AGENT_ENDPOINT=ws://192.168.100.105:3001
      - AGENT_INVITATION_IMAGE_URL=http://192.168.100.105:3001/avatar.png
      - PUBLIC_API_BASE_URL=http://192.168.100.105:3001
      - AGENT_LABEL=Chatbot Agent
      - USE_CORS=true
      - EVENTS_BASE_URL=http://chatbot-backend:5000
      - AGENT_INVITATION_BASE_URL=https://hologram.zone/
    volumes:
      - ./afj:/root/.afj

  chatbot-backend:
    build: 
      context: ../..
      dockerfile: ./examples/chatbot/Dockerfile
    image: vs-agent-chatbot
    depends_on:
      - vs-agent
    container_name: chatbot-backend
    restart: always
    networks:
      - chatbot
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - VS_AGENT_ADMIN_BASE_URL=http://chatbot-vs-agent:3000

networks:
  chatbot:
