name: Continuous Deployment

on:
  push:
    branches: [main, 'release/**']

permissions:
  id-token: write   # Required for OIDC
  contents: write   # Required for updating npm versions
  issues: write
  pull-requests: write

env:
  IMAGE_NAME: 'vs-agent'
  DEMO_CHATBOT_IMAGE_NAME: 'vs-agent-demo-chatbot-backend'

jobs:
  resolve-version:
    uses: 2060-io/organization/.github/workflows/resolve-version-call.yml@main

  docker:
    needs: resolve-version
    if: needs.resolve-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest

    env:
      RELEASE_TYPE: ${{ needs.resolve-version.outputs.release-type }}
      RELEASE_VERSION: ${{ needs.resolve-version.outputs.release-version }}
      RELEASE_MAJOR: ${{ needs.resolve-version.outputs.release-major }}
      RELEASE_MINOR: ${{ needs.resolve-version.outputs.release-minor }}
      RELEASE_PATCH: ${{ needs.resolve-version.outputs.release-patch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute tags
        id: compute-tags
        run: |
          if [ "$RELEASE_TYPE" = "stable" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "SUFFIX=" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
            echo "SUFFIX=-dev" >> $GITHUB_ENV
            echo "RELEASE_PATCH_SHORT=${RELEASE_PATCH:0:1}" >> $GITHUB_ENV
          fi

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      # VS Agent
      - name: Build & push ${{ env.IMAGE_NAME }} dev tags
        if: env.RELEASE_TYPE == 'dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/vs-agent/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}.${{ env.RELEASE_MINOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}.${{ env.RELEASE_MINOR }}.${{ env.RELEASE_PATCH_SHORT }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

      # Split stable and dev tag builds custom tags for each release type.
      - name: Build & push ${{ env.IMAGE_NAME }} stable release tags
        if: env.RELEASE_TYPE == 'stable'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/vs-agent/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}.${{ env.RELEASE_MINOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

      # Chatbot Demo (Split container build to vs agent dependency)
      - name: Build & push ${{ env.DEMO_CHATBOT_IMAGE_NAME }} dev tags
        if: env.RELEASE_TYPE == 'dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./examples/chatbot/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}.${{ env.RELEASE_MINOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}.${{ env.RELEASE_MINOR }}.${{ env.RELEASE_PATCH_SHORT }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

      # Split stable and dev tag builds custom tags for each release type.
      - name: Build & push ${{ env.DEMO_CHATBOT_IMAGE_NAME }} stable release tags
        if: env.RELEASE_TYPE == 'stable'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./examples/chatbot/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:v${{ env.RELEASE_MAJOR }}.${{ env.RELEASE_MINOR }}${{ env.SUFFIX }}
            ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.DEMO_CHATBOT_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

  helm:
    needs: [resolve-version, docker]
    if: needs.resolve-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ needs.resolve-version.outputs.release-type }}
      RELEASE_VERSION: ${{ needs.resolve-version.outputs.release-version }}
      RELEASE_MAJOR: ${{ needs.resolve-version.outputs.release-major }}
      RELEASE_MINOR: ${{ needs.resolve-version.outputs.release-minor }}
      RELEASE_PATCH: ${{ needs.resolve-version.outputs.release-patch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Push Helm chart to Docker Hub OCI repo
        run: |
          if [ "$RELEASE_TYPE" = "stable" ]; then
            TAGS=("${RELEASE_VERSION}")
          else
            TAGS=(
              "v${RELEASE_MAJOR}.${RELEASE_MINOR}.${RELEASE_PATCH:0:1}-dev"
              "${RELEASE_VERSION}"
            )
          fi
          CHART_NAME=$(grep '^name:' ./charts/vs-agent/Chart.yaml | awk '{print $2}')
          for tag in "${TAGS[@]}"; do
            helm dependency update ./charts/vs-agent
            helm package ./charts/vs-agent --version $tag -d ./charts
            helm push ./charts/${CHART_NAME}-$tag.tgz oci://docker.io/${{ secrets.DOCKER_HUB_LOGIN }}
          done

      - name: Push Helm chart Chatbot Demo to Docker Hub OCI repo
        run: |
          if [ "$RELEASE_TYPE" = "stable" ]; then
            TAGS=("${RELEASE_VERSION}")
          else
            TAGS=(
              "v${RELEASE_MAJOR}.${RELEASE_MINOR}.${RELEASE_PATCH:0:1}-dev"
              "${RELEASE_VERSION}"
            )
          fi
          # update the dependencies version in the Chart.yaml
          sed -i "s/^\([[:space:]]*version:\).*/\1 $RELEASE_VERSION/" ./charts/chatbot/Chart.yaml
          CHART_NAME=$(grep '^name:' ./charts/chatbot/Chart.yaml | awk '{print $2}')
          for tag in "${TAGS[@]}"; do
            helm dependency update ./charts/chatbot
            helm package ./charts/chatbot --version $tag -d ./charts
            helm push ./charts/${CHART_NAME}-$tag.tgz oci://docker.io/${{ secrets.DOCKER_HUB_LOGIN }}
          done

  npm-publish:
    needs: [resolve-version]
    if: needs.resolve-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ needs.resolve-version.outputs.release-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pnpm version has been pinned in package.json
      - name: Setup node v24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Corepack pnpm
        run: corepack enable
          
      - name: Install dependencies
        run: |
          pnpm install
          pnpm build

      - name: Set version for apps and packages
        run: |
          pnpm -r --topological version "$RELEASE_VERSION"

      # --no-git-checks is used due to topological version updating.
      - name: Publish NPM packages
        run: |
          pnpm -r publish --no-git-checks --access public

