name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: 2060-io/organization/.github/workflows/2060-linter-call.yml@5f813454d8962db006c4e4466f3af1cf4af8dfa4 # main

  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./apps/vs-agent/Dockerfile
            target: vs-agent
          - dockerfile: ./apps/vs-agent/Dockerfile
            target: vs-agent-chat
          - dockerfile: ./apps/vs-agent/Dockerfile
            target: vs-agent-mrtd
          - dockerfile: ./examples/chatbot/Dockerfile
          - dockerfile: ./examples/verifier/Dockerfile
          - dockerfile: ./examples/nestjs-vs/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build ${{ matrix.dockerfile }} ${{ matrix.target }}
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
